### ISSUE TITLE
Caputing page screenshot not working when the page title is too long

### ISSUE THREAD

**Issue by Polonco** [coddingtonbear/obsidian-web#24]
I want to save a tweet using the caputure page screenshot but I receive an error message. Every other URL is saved properly.

Tweet URL
https://is.gd/vJeGNw

Error message
![image](https://user-images.githubusercontent.com/110239199/181764725-73c977c0-d38d-4632-8212-ce5d5838da70.png)

Extension setting
![image](https://user-images.githubusercontent.com/110239199/181764912-877a2360-5dc4-498c-8ed9-baba3afe6e84.png)

**Comment by coddingtonbear** [comment]
I see that you're sure that this is because the filename is too long rather than any of the other possible reasons for this error, but the screenshot you've shown above can be reported for a variety of reasons.  What error do you see in your Obsidian console (Ctrl+Shift+I) when this happens?

**Comment by coddingtonbear** [comment]
Reading about Windows, it does look like in certain situations there's a path limit of 260 characters, and although I haven't counted the characters in your message, it does look plausible that you're going past that limit.   Unfortunately, adding some sort of functionality for trimming the length of a generated filename to fit within those limits would require awareness of:

- What OS Obsidian is running on.  Not everybody is on Windows these days (I myself, for example, don't run it on Windows), and other platforms and filesystems don't have this limitation.  Additionally this is adjustable via a registry setting on Windows; so the limitation could differ even for the same platform and filesystem.
- What your vault's path is.  Although you can infer the path from the error message Obsidian is reporting that back, this plugin isn't directly aware of that detail because it's generally none of it's business.

Since this plugin _does_ show you the path it generated for you and gives you the option of changing it, I'm going to close this as "won't fix".  If you run into this in the future, just re-open the plugin window and shorten the path manually to fit into the unique constraints of your personal environment.  

Cheers & good luck!
