### ISSUE TITLE
Cannot use timezone patterns in date format parameter

### ISSUE THREAD

**Issue by csu** [coddingtonbear/obsidian-web#39]
The timezone patterns from date-fns (e.g. `xx` and `XX`) don't seem to work when used in the date format string.

Example format string:
```
date: {{date YYYY-MM-DD HH-mmxx}}
```

Results in:
```
date: 2022-09-19 02:00:35
```

**Comment by coddingtonbear** [comment]
I understand that you're trying to save time, but it's very important that each problem be filed as a separate github issue so that the discussion following it can be relevant to the whole described problem instead of potentially just half of it; toward that end, I've moved your second issue to #40 and will discuss only the first issue here.

**Comment by coddingtonbear** [comment]
I'm not able to reproduce the problem you've described, but I also see that you're missing quotes around your format string in the manner described in the in-product docs:

> {{date}}: Displays a timestamp. By default this uses the format "yyyy-MM-dd HH:mm:ss", but you can configure the format used by providing a second parameter; for example:{{date "EEEE, MMMM do"}} would display a timestamp like "Friday, February 18th". See [here](https://date-fns.org/v2.28.0/docs/format) for a full list of formatting codes.

Note that there are double-quotes around the format string; they are important, and without them your date will be formatted using the default format, which is the one you're seeing.
